import BriefList from "./BriefList.jsx";

export default function BidBriefCard({ bidBrief }) {
  if (!bidBrief) {
    return (
      <div className="bidBriefCard">
        <div className="briefHeader">
          <div>
            <p className="eyebrow dark">Bid Brief</p>
            <h2>No bid brief available yet</h2>
          </div>
          <span className="briefMode">rules_only</span>
        </div>
        <p className="muted">Analyze the RFP first to generate a rule-based executive bid brief.</p>
      </div>
    );
  }

  return (
    <div className="bidBriefCard">
      <div className="briefHeader">
        <div>
          <p className="eyebrow dark">Bid Brief</p>
          <h2>Executive Bid Summary</h2>
          <p className="muted">
            Generated by {bidBrief.generated_by} · Mode: {bidBrief.ai_mode}
          </p>
        </div>
        <span className="briefMode">{bidBrief.ai_mode}</span>
      </div>

      <div className="briefExecutive">
        <strong>Executive Summary</strong>
        <p>{bidBrief.executive_summary}</p>
      </div>

      <div className="briefGrid">
        <BriefList title="Key Risks" items={bidBrief.key_risks || []} />
        <BriefList title="Clarification Focus" items={bidBrief.clarification_focus || []} />
        <BriefList title="Next Actions" items={bidBrief.next_actions || []} />
        <BriefList title="Assumptions" items={bidBrief.assumptions || []} />
      </div>
    </div>
  );
}
