def _norm(value: str | None) -> str:
    return " ".join(str(value or "").strip().split())


def _key(value: str | None) -> str:
    return _norm(value).lower()


def _category_for_evidence(name: str) -> str:
    lower = name.lower()

    if any(k in lower for k in ["nib", "npwp", "administrative", "submission", "surat penawaran", "meterai", "bermeterai"]):
        return "administrative"

    if any(k in lower for k in ["commercial", "pricing", "tax", "payment", "validity", "exclusion"]):
        return "commercial"

    if any(k in lower for k in ["architecture", "solution", "sla", "support", "service scope", "responsibility"]):
        return "solution"

    if any(k in lower for k in ["methodology", "delivery", "timeline", "transition", "acceptance"]):
        return "delivery"

    if any(k in lower for k in ["security", "compliance", "data protection", "certification", "policy", "audit"]):
        return "security_compliance"

    if any(k in lower for k in ["cv", "resource", "availability", "staff", "role"]):
        return "staffing"

    return "general"


def _priority_for_evidence(category: str) -> str:
    if category in {"administrative", "commercial", "security_compliance"}:
        return "high"

    if category in {"solution", "delivery", "staffing"}:
        return "medium"

    return "medium"


def _owner_for_category(category: str, fallback_owner: str | None = None) -> str:
    if fallback_owner:
        return fallback_owner

    mapping = {
        "administrative": "bid_manager",
        "commercial": "commercial_team",
        "solution": "solution_architect",
        "delivery": "delivery_manager",
        "security_compliance": "security_compliance_team",
        "staffing": "resource_manager",
        "general": "bid_manager",
    }

    return mapping.get(category, "bid_manager")


def generate_evidence_pack_items(metadata=None, response_items=None, proposal_sections=None) -> list[dict]:
    response_items = response_items or []
    proposal_sections = proposal_sections or []

    bucket = {}

    def add_item(
        *,
        name,
        owner=None,
        source_type="generated",
        source_id=None,
        requirement_id=None,
        response_item_id=None,
        proposal_section_id=None,
        notes=None,
    ):
        cleaned = _norm(name)
        if not cleaned:
            return

        key = _key(cleaned)
        category = _category_for_evidence(cleaned)

        if key not in bucket:
            bucket[key] = {
                "evidence_name": cleaned,
                "evidence_category": category,
                "owner": _owner_for_category(category, owner),
                "status": "open",
                "priority": _priority_for_evidence(category),
                "source_type": source_type,
                "source_ids": [],
                "related_requirement_ids": [],
                "related_response_item_ids": [],
                "related_proposal_section_ids": [],
                "notes": notes or "Generated by rule-based evidence pack generator v1",
                "generation_mode": "rules_only",
            }

        item = bucket[key]

        if source_id is not None and source_id not in item["source_ids"]:
            item["source_ids"].append(source_id)

        if requirement_id is not None and requirement_id not in item["related_requirement_ids"]:
            item["related_requirement_ids"].append(requirement_id)

        if response_item_id is not None and response_item_id not in item["related_response_item_ids"]:
            item["related_response_item_ids"].append(response_item_id)

        if proposal_section_id is not None and proposal_section_id not in item["related_proposal_section_ids"]:
            item["related_proposal_section_ids"].append(proposal_section_id)

    if metadata:
        for req in metadata.submission_requirements or []:
            add_item(
                name=req,
                owner="bid_manager",
                source_type="metadata",
                source_id=metadata.id,
                notes="Detected from RFP metadata submission requirements.",
            )

    for response_item in response_items:
        for evidence in response_item.evidence_needed or []:
            add_item(
                name=evidence,
                owner=response_item.owner,
                source_type="response_plan",
                source_id=response_item.id,
                requirement_id=response_item.requirement_id,
                response_item_id=response_item.id,
                notes="Derived from response plan evidence checklist.",
            )

    for section in proposal_sections:
        for evidence in section.evidence_needed or []:
            add_item(
                name=evidence,
                owner=section.owner,
                source_type="proposal_outline",
                source_id=section.id,
                proposal_section_id=section.id,
                notes="Derived from proposal outline evidence checklist.",
            )

    return sorted(
        bucket.values(),
        key=lambda item: (
            {"high": 0, "medium": 1, "low": 2}.get(item["priority"], 9),
            item["evidence_category"],
            item["evidence_name"].lower(),
        ),
    )
