from pathlib import Path
from datetime import datetime
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from app.services.i18n_service import localized_label


HEADER_FILL = PatternFill("solid", fgColor="1F2937")
HEADER_FONT = Font(color="FFFFFF", bold=True)
TITLE_FONT = Font(size=16, bold=True, color="111827")
SUBTITLE_FONT = Font(size=11, color="475569")
THIN_BORDER = Border(
    left=Side(style="thin", color="E5E7EB"),
    right=Side(style="thin", color="E5E7EB"),
    top=Side(style="thin", color="E5E7EB"),
    bottom=Side(style="thin", color="E5E7EB"),
)


def _autosize_columns(ws, max_width: int = 70):
    for column_cells in ws.columns:
        length = 0
        column_letter = get_column_letter(column_cells[0].column)
        for cell in column_cells:
            value = cell.value
            if value is None:
                continue
            length = max(length, len(str(value)))
        ws.column_dimensions[column_letter].width = min(max(length + 2, 12), max_width)


def _style_table(ws, header_row: int):
    for cell in ws[header_row]:
        cell.fill = HEADER_FILL
        cell.font = HEADER_FONT
        cell.alignment = Alignment(vertical="center", wrap_text=True)
        cell.border = THIN_BORDER

    for row in ws.iter_rows(min_row=header_row + 1):
        for cell in row:
            cell.alignment = Alignment(vertical="top", wrap_text=True)
            cell.border = THIN_BORDER


def _style_risk_cell(cell, risk_level: str | None):
    if risk_level == "high":
        cell.fill = PatternFill("solid", fgColor="FEE2E2")
        cell.font = Font(color="991B1B", bold=True)
    elif risk_level == "medium":
        cell.fill = PatternFill("solid", fgColor="FEF3C7")
        cell.font = Font(color="92400E", bold=True)
    elif risk_level == "low":
        cell.fill = PatternFill("solid", fgColor="DCFCE7")
        cell.font = Font(color="166534", bold=True)


def _style_priority_cell(cell, priority: str | None):
    if priority == "high":
        cell.fill = PatternFill("solid", fgColor="FEE2E2")
        cell.font = Font(color="991B1B", bold=True)
    elif priority == "medium":
        cell.fill = PatternFill("solid", fgColor="FEF3C7")
        cell.font = Font(color="92400E", bold=True)
    elif priority == "low":
        cell.fill = PatternFill("solid", fgColor="DCFCE7")
        cell.font = Font(color="166534", bold=True)


def export_project_checklist(
    project,
    documents,
    requirements,
    output_path: str,
    clarifications=None,
    bid_brief=None,
    response_items=None,
    evidence_items=None,
    decision_gate=None,
    output_language: str = "en",
) -> str:
    L = lambda label: localized_label(label, output_language)
    clarifications = clarifications or []
    bid_brief = bid_brief or {}
    response_items = response_items or []
    evidence_items = evidence_items or []

    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)

    wb = Workbook()

    # Summary Sheet
    ws = wb.active
    ws.title = "Summary"

    ws["A1"] = "BidReady AI - Tender Intelligence Report"
    ws["A1"].font = TITLE_FONT

    ws["A2"] = "Generated by BidReady AI - Tender Intelligence Platform"
    ws["A2"].font = SUBTITLE_FONT

    summary_rows = [
        ("Project ID", project.id),
        ("Project Title", project.title),
        ("Client / Issuer", project.issuer or "-"),
        ("Service Domain", project.tender_type or "-"),
        ("Status", project.status),
        ("Created At", str(project.created_at)),
        ("Generated At", datetime.utcnow().isoformat()),
        ("Document Count", len(documents)),
        ("Requirement Count", len(requirements)),
        ("High Risk Requirement Count", len([r for r in requirements if r.risk_level == "high"])),
        ("Clarification Question Count", len(clarifications)),
        ("Open Clarification Count", len([q for q in clarifications if q.status == "open"])),
        ("High Priority Clarification Count", len([q for q in clarifications if q.priority == "high"])),
    ]

    start_row = 4
    for idx, (label, value) in enumerate(summary_rows, start=start_row):
        ws.cell(row=idx, column=1, value=label)
        ws.cell(row=idx, column=2, value=value)
        ws.cell(row=idx, column=1).font = Font(bold=True)
        ws.cell(row=idx, column=1).border = THIN_BORDER
        ws.cell(row=idx, column=2).border = THIN_BORDER

    _autosize_columns(ws)

    # Bid Brief Sheet
    ws_brief = wb.create_sheet("Bid Brief")

    ws_brief["A1"] = "BidReady AI - Executive Bid Brief"
    ws_brief["A1"].font = TITLE_FONT

    ws_brief["A2"] = f"Generated by: {bid_brief.get('generated_by', '-')}"
    ws_brief["A2"].font = SUBTITLE_FONT

    ws_brief["A3"] = f"AI Mode: {bid_brief.get('ai_mode', '-')}"
    ws_brief["A3"].font = SUBTITLE_FONT

    ws_brief["A5"] = "Executive Summary"
    ws_brief["A5"].font = Font(bold=True)
    ws_brief["A6"] = bid_brief.get("executive_summary", "-")
    ws_brief["A6"].alignment = Alignment(wrap_text=True, vertical="top")

    brief_sections = [
        ("Key Risks", bid_brief.get("key_risks", [])),
        ("Clarification Focus", bid_brief.get("clarification_focus", [])),
        ("Next Actions", bid_brief.get("next_actions", [])),
        ("Assumptions", bid_brief.get("assumptions", [])),
    ]

    row = 8
    for title, items in brief_sections:
        ws_brief.cell(row=row, column=1, value=title)
        ws_brief.cell(row=row, column=1).font = Font(bold=True)
        row += 1

        if not items:
            ws_brief.cell(row=row, column=1, value="-")
            row += 1
        else:
            for item in items:
                ws_brief.cell(row=row, column=1, value=f"• {item}")
                ws_brief.cell(row=row, column=1).alignment = Alignment(wrap_text=True, vertical="top")
                row += 1

        row += 1

    ws_brief.column_dimensions["A"].width = 120

    # Decision Gate Sheet
    ws_dec = wb.create_sheet(L("Decision Gate"))

    ws_dec["A1"] = L("BidReady AI - Executive Decision Gate")
    ws_dec["A2"] = L("Bid / No-Bid decision support generated from readiness, requirements, response plan, proposal outline, and evidence pack.")

    if decision_gate:
        decision_rows = [
            (L("Decision Status"), decision_gate.decision_status),
            (L("Recommendation"), decision_gate.recommendation),
            (L("Readiness Score"), decision_gate.readiness_score),
            (L("Confidence"), decision_gate.confidence),
            (L("Owner"), decision_gate.owner),
            (L("Due Date"), decision_gate.due_date),
            (L("Generation Mode"), decision_gate.generation_mode),
            ("Created At", str(decision_gate.created_at) if decision_gate.created_at else None),
            ("Updated At", str(decision_gate.updated_at) if decision_gate.updated_at else None),
        ]

        row = 4
        for label, value in decision_rows:
            ws_dec.cell(row=row, column=1, value=label)
            ws_dec.cell(row=row, column=2, value=value)
            row += 1

        row += 1
        ws_dec.cell(row=row, column=1, value=L("Executive Summary"))
        ws_dec.cell(row=row, column=2, value=decision_gate.executive_summary)
        row += 2

        sections = [
            (L("Key Reasons"), decision_gate.key_reasons or []),
            (L("Blockers"), decision_gate.blockers or []),
            (L("Required Approvals"), decision_gate.required_approvals or []),
            (L("Next Actions"), decision_gate.next_actions or []),
        ]

        for title, items in sections:
            ws_dec.cell(row=row, column=1, value=title)
            row += 1

            if not items:
                ws_dec.cell(row=row, column=2, value="-")
                row += 1
            else:
                for item in items:
                    ws_dec.cell(row=row, column=2, value=item)
                    row += 1

            row += 1

        ws_dec.cell(row=row, column=1, value=L("Notes"))
        ws_dec.cell(row=row, column=2, value=decision_gate.notes)
    else:
        ws_dec["A4"] = L("Decision gate has not been generated yet.")

    _style_table(ws_dec, 4)
    _autosize_columns(ws_dec)
    ws_dec.freeze_panes = "A4"

    # Response Plan Sheet
    ws_resp = wb.create_sheet("Response Plan")

    response_headers = [
        "ID",
        "Requirement ID",
        "Category",
        "Requirement",
        "Compliance Status",
        "Owner",
        "Status",
        "Response Strategy",
        "Draft Response",
        "Evidence Needed",
        "Risks",
        "Assumptions",
        "Source Page",
        "Evidence Quote",
        "Notes",
        "Confidence",
        "Generation Mode",
    ]

    for col_idx, header in enumerate(response_headers, start=1):
        ws_resp.cell(row=1, column=col_idx, value=header)

    for row_idx, item in enumerate(response_items, start=2):
        ws_resp.cell(row=row_idx, column=1, value=item.id)
        ws_resp.cell(row=row_idx, column=2, value=item.requirement_id)
        ws_resp.cell(row=row_idx, column=3, value=item.category)
        ws_resp.cell(row=row_idx, column=4, value=item.requirement_text)
        ws_resp.cell(row=row_idx, column=5, value=item.compliance_status)
        ws_resp.cell(row=row_idx, column=6, value=item.owner)
        ws_resp.cell(row=row_idx, column=7, value=item.status)
        ws_resp.cell(row=row_idx, column=8, value=item.response_strategy)
        ws_resp.cell(row=row_idx, column=9, value=item.draft_response)
        ws_resp.cell(row=row_idx, column=10, value="\n".join(item.evidence_needed or []))
        ws_resp.cell(row=row_idx, column=11, value="\n".join(item.risks or []))
        ws_resp.cell(row=row_idx, column=12, value="\n".join(item.assumptions or []))
        ws_resp.cell(row=row_idx, column=13, value=item.source_page)
        ws_resp.cell(row=row_idx, column=14, value=item.evidence_quote)
        ws_resp.cell(row=row_idx, column=15, value=item.notes)
        ws_resp.cell(row=row_idx, column=16, value=item.confidence)
        ws_resp.cell(row=row_idx, column=17, value=item.generation_mode)

        compliance_cell = ws_resp.cell(row=row_idx, column=5)
        if item.compliance_status == "likely_compliant":
            compliance_cell.fill = PatternFill("solid", fgColor="DCFCE7")
            compliance_cell.font = Font(color="166534", bold=True)
        elif item.compliance_status in {"partially_compliant", "needs_review", "needs_clarification"}:
            compliance_cell.fill = PatternFill("solid", fgColor="FEF3C7")
            compliance_cell.font = Font(color="92400E", bold=True)
        elif item.compliance_status in {"non_compliant", "blocked"}:
            compliance_cell.fill = PatternFill("solid", fgColor="FEE2E2")
            compliance_cell.font = Font(color="991B1B", bold=True)

    _style_table(ws_resp, 1)
    _autosize_columns(ws_resp)
    ws_resp.freeze_panes = "A2"
    ws_resp.auto_filter.ref = ws_resp.dimensions

    # Evidence Pack Sheet
    ws_evd = wb.create_sheet("Evidence Pack")

    evidence_headers = [
        "ID",
        "Evidence Name",
        "Category",
        "Owner",
        "Priority",
        "Status",
        "Source Type",
        "Source IDs",
        "Related Requirement IDs",
        "Related Response Item IDs",
        "Related Proposal Section IDs",
        "Notes",
        "Generation Mode",
    ]

    for col_idx, header in enumerate(evidence_headers, start=1):
        ws_evd.cell(row=1, column=col_idx, value=header)

    for row_idx, item in enumerate(evidence_items, start=2):
        ws_evd.cell(row=row_idx, column=1, value=item.id)
        ws_evd.cell(row=row_idx, column=2, value=item.evidence_name)
        ws_evd.cell(row=row_idx, column=3, value=item.evidence_category)
        ws_evd.cell(row=row_idx, column=4, value=item.owner)
        ws_evd.cell(row=row_idx, column=5, value=item.priority)
        ws_evd.cell(row=row_idx, column=6, value=item.status)
        ws_evd.cell(row=row_idx, column=7, value=item.source_type)
        ws_evd.cell(row=row_idx, column=8, value=", ".join([str(x) for x in item.source_ids or []]))
        ws_evd.cell(row=row_idx, column=9, value=", ".join([str(x) for x in item.related_requirement_ids or []]))
        ws_evd.cell(row=row_idx, column=10, value=", ".join([str(x) for x in item.related_response_item_ids or []]))
        ws_evd.cell(row=row_idx, column=11, value=", ".join([str(x) for x in item.related_proposal_section_ids or []]))
        ws_evd.cell(row=row_idx, column=12, value=item.notes)
        ws_evd.cell(row=row_idx, column=13, value=item.generation_mode)

        priority_cell = ws_evd.cell(row=row_idx, column=5)
        if item.priority == "high":
            priority_cell.fill = PatternFill("solid", fgColor="FEE2E2")
            priority_cell.font = Font(color="991B1B", bold=True)
        elif item.priority == "medium":
            priority_cell.fill = PatternFill("solid", fgColor="FEF3C7")
            priority_cell.font = Font(color="92400E", bold=True)
        elif item.priority == "low":
            priority_cell.fill = PatternFill("solid", fgColor="DCFCE7")
            priority_cell.font = Font(color="166534", bold=True)

        status_cell = ws_evd.cell(row=row_idx, column=6)
        if item.status == "validated":
            status_cell.fill = PatternFill("solid", fgColor="DCFCE7")
            status_cell.font = Font(color="166534", bold=True)
        elif item.status in {"requested", "received"}:
            status_cell.fill = PatternFill("solid", fgColor="DBEAFE")
            status_cell.font = Font(color="1E3A8A", bold=True)
        elif item.status == "blocked":
            status_cell.fill = PatternFill("solid", fgColor="FEE2E2")
            status_cell.font = Font(color="991B1B", bold=True)

    _style_table(ws_evd, 1)
    _autosize_columns(ws_evd)
    ws_evd.freeze_panes = "A2"
    ws_evd.auto_filter.ref = ws_evd.dimensions

    # Requirements Sheet
    ws_req = wb.create_sheet("Requirements")
    headers = [
        "ID",
        "Category",
        "Requirement",
        "Priority",
        "Risk Level",
        "Source Page",
        "Evidence Quote",
        "Suggested Owner",
        "Status",
        "Confidence",
        "Reviewer Notes",
    ]

    for col_idx, header in enumerate(headers, start=1):
        ws_req.cell(row=1, column=col_idx, value=header)

    for row_idx, req in enumerate(requirements, start=2):
        ws_req.cell(row=row_idx, column=1, value=req.id)
        ws_req.cell(row=row_idx, column=2, value=req.category)
        ws_req.cell(row=row_idx, column=3, value=req.requirement_text)
        ws_req.cell(row=row_idx, column=4, value=req.priority)
        ws_req.cell(row=row_idx, column=5, value=req.risk_level)
        ws_req.cell(row=row_idx, column=6, value=req.source_page)
        ws_req.cell(row=row_idx, column=7, value=req.evidence_quote)
        ws_req.cell(row=row_idx, column=8, value=req.suggested_owner)
        ws_req.cell(row=row_idx, column=9, value=req.status)
        ws_req.cell(row=row_idx, column=10, value=req.confidence)
        ws_req.cell(row=row_idx, column=11, value=req.notes)

        _style_risk_cell(ws_req.cell(row=row_idx, column=5), req.risk_level)

    _style_table(ws_req, 1)
    _autosize_columns(ws_req)
    ws_req.freeze_panes = "A2"
    ws_req.auto_filter.ref = ws_req.dimensions

    # Clarification Questions Sheet
    ws_clar = wb.create_sheet("Clarification Questions")
    clarification_headers = [
        "ID",
        "Requirement ID",
        "Category",
        "Question",
        "Reason",
        "Priority",
        "Risk Level",
        "Source Page",
        "Owner",
        "Status",
        "Notes",
    ]

    for col_idx, header in enumerate(clarification_headers, start=1):
        ws_clar.cell(row=1, column=col_idx, value=header)

    for row_idx, q in enumerate(clarifications, start=2):
        ws_clar.cell(row=row_idx, column=1, value=q.id)
        ws_clar.cell(row=row_idx, column=2, value=q.requirement_id)
        ws_clar.cell(row=row_idx, column=3, value=q.category)
        ws_clar.cell(row=row_idx, column=4, value=q.question_text)
        ws_clar.cell(row=row_idx, column=5, value=q.reason)
        ws_clar.cell(row=row_idx, column=6, value=q.priority)
        ws_clar.cell(row=row_idx, column=7, value=q.risk_level)
        ws_clar.cell(row=row_idx, column=8, value=q.source_page)
        ws_clar.cell(row=row_idx, column=9, value=q.owner)
        ws_clar.cell(row=row_idx, column=10, value=q.status)
        ws_clar.cell(row=row_idx, column=11, value=q.notes)

        _style_priority_cell(ws_clar.cell(row=row_idx, column=6), q.priority)
        _style_risk_cell(ws_clar.cell(row=row_idx, column=7), q.risk_level)

    _style_table(ws_clar, 1)
    _autosize_columns(ws_clar)
    ws_clar.freeze_panes = "A2"
    ws_clar.auto_filter.ref = ws_clar.dimensions

    # Documents Sheet
    ws_doc = wb.create_sheet("Documents")
    doc_headers = [
        "ID",
        "Filename",
        "Content Type",
        "File Size",
        "Hash",
        "Page Count",
        "Processing Status",
        "Extracted Text Path",
        "Created At",
    ]

    for col_idx, header in enumerate(doc_headers, start=1):
        ws_doc.cell(row=1, column=col_idx, value=header)

    for row_idx, doc in enumerate(documents, start=2):
        ws_doc.cell(row=row_idx, column=1, value=doc.id)
        ws_doc.cell(row=row_idx, column=2, value=doc.filename)
        ws_doc.cell(row=row_idx, column=3, value=doc.content_type)
        ws_doc.cell(row=row_idx, column=4, value=doc.file_size)
        ws_doc.cell(row=row_idx, column=5, value=doc.file_hash)
        ws_doc.cell(row=row_idx, column=6, value=doc.page_count)
        ws_doc.cell(row=row_idx, column=7, value=doc.processing_status)
        ws_doc.cell(row=row_idx, column=8, value=doc.extracted_text_path)
        ws_doc.cell(row=row_idx, column=9, value=str(doc.created_at))

    _style_table(ws_doc, 1)
    _autosize_columns(ws_doc)
    ws_doc.freeze_panes = "A2"
    ws_doc.auto_filter.ref = ws_doc.dimensions

    wb.save(output)
    return str(output)
