import re
from typing import Any

from sqlalchemy.orm import Session

from app.models.project_language import TenderProjectLanguageSetting


def get_project_output_language(db: Session, project_id: int) -> str:
    setting = (
        db.query(TenderProjectLanguageSetting)
        .filter(TenderProjectLanguageSetting.project_id == project_id)
        .first()
    )

    if not setting:
        return "en"

    return setting.output_language or "en"


DIRECT_ID_REPLACEMENTS = {
    # Decision Gate recommendations
    "Needs Executive Review Before Bid Commitment": "Perlu Review Eksekutif Sebelum Komitmen Bid",
    "Recommend No-Bid or Executive Exception Review": "Rekomendasi No-Bid atau Review Eksepsi Eksekutif",
    "Recommend Bid - Ready for Final Approval": "Rekomendasi Bid - Siap untuk Persetujuan Final",
    "Recommend Bid with Controlled Risk Review": "Rekomendasi Bid dengan Review Risiko Terkendali",

    # Common headings / notes
    "Generated by rule-based decision gate generator v1": "Dihasilkan oleh generator decision gate berbasis rule v1",
    "Generated by rule-based evidence pack generator v1": "Dihasilkan oleh generator evidence pack berbasis rule v1",
    "Detected from RFP metadata submission requirements.": "Terdeteksi dari metadata RFP pada persyaratan submit dokumen.",
    "Derived from response plan evidence checklist.": "Diturnkan dari checklist evidence pada response plan.",
    "Derived from proposal outline evidence checklist.": "Diturnkan dari checklist evidence pada proposal outline.",

    # Common list items
    "Final bid manager approval before submission.": "Persetujuan final dari bid manager sebelum submission.",
    "Proceed to final executive review and submission approval.": "Lanjut ke review eksekutif final dan persetujuan submission.",
    "Generate response plan from requirement matrix.": "Generate response plan dari requirement matrix.",
    "Generate proposal outline from response plan.": "Generate proposal outline dari response plan.",
    "Generate evidence pack and assign evidence owners.": "Generate evidence pack dan assign owner evidence.",
    "Complete human review for all needs_review requirements.": "Selesaikan review manual untuk semua requirement berstatus needs_review.",
    "Resolve open clarification questions or document assumptions.": "Selesaikan clarification question yang masih open atau dokumentasikan asumsi.",
    "Collect and validate high-priority evidence before submission.": "Kumpulkan dan validasi evidence prioritas tinggi sebelum submission.",
    "Move proposal sections from draft to in_review or ready.": "Pindahkan proposal section dari draft ke in_review atau ready.",

    # Generic terms often used in generated output
    "Executive Summary": "Ringkasan Eksekutif",
    "Key Reasons": "Alasan Utama",
    "Blockers": "Blocker",
    "Required Approvals": "Approval yang Dibutuhkan",
    "Next Actions": "Tindak Lanjut",
    "Evidence Needed": "Evidence yang Dibutuhkan",
    "Risks / Review Notes": "Risiko / Catatan Review",
    "Section Notes": "Catatan Section",
    "Purpose": "Tujuan",
    "Content Outline": "Outline Konten",
    "Draft Content": "Draft Konten",
}


REGEX_ID_REPLACEMENTS = [
    (
        r"Readiness score is (\d+), indicating additional review is required before commitment\.",
        r"Skor readiness adalah \1, sehingga masih diperlukan review tambahan sebelum komitmen bid.",
    ),
    (
        r"Readiness score is (\d+), indicating the bid can proceed with controlled review\.",
        r"Skor readiness adalah \1, sehingga bid dapat dilanjutkan dengan review risiko terkendali.",
    ),
    (
        r"(\d+) requirement item\(s\) have been extracted and structured\.",
        r"\1 requirement berhasil diekstrak dan distrukturkan.",
    ),
    (
        r"(\d+) response plan item\(s\) are available for proposal preparation\.",
        r"\1 item response plan tersedia untuk persiapan proposal.",
    ),
    (
        r"(\d+) proposal outline section\(s\) have been prepared\.",
        r"\1 section proposal outline sudah disiapkan.",
    ),
    (
        r"(\d+) evidence item\(s\) are tracked in the evidence pack\.",
        r"\1 item evidence sudah tercatat di evidence pack.",
    ),
    (
        r"(\d+) requirement\(s\) still need owner review\.",
        r"\1 requirement masih membutuhkan review owner.",
    ),
    (
        r"(\d+) clarification question\(s\) remain open\.",
        r"\1 clarification question masih open.",
    ),
    (
        r"(\d+) requirement\(s\) are blocked\.",
        r"\1 requirement berstatus blocked.",
    ),
    (
        r"(\d+) response item\(s\) are marked non-compliant\.",
        r"\1 response item ditandai non-compliant.",
    ),
    (
        r"(\d+) response item\(s\) are blocked\.",
        r"\1 response item berstatus blocked.",
    ),
    (
        r"(\d+) evidence item\(s\) are blocked\.",
        r"\1 evidence item berstatus blocked.",
    ),
    (
        r"(\d+) high-priority clarification question\(s\) are still present\.",
        r"\1 clarification question prioritas tinggi masih perlu ditindaklanjuti.",
    ),
    (
        r"(\d+) high-priority evidence item\(s\) are still open/requested\.",
        r"\1 evidence prioritas tinggi masih open/requested.",
    ),
    (
        r"Bid Manager approval for high-risk and blocked requirements\.",
        r"Approval Bid Manager untuk requirement high-risk dan blocked.",
    ),
    (
        r"Solution / Delivery approval for blocked or non-compliant response items\.",
        r"Approval Solution / Delivery untuk response item yang blocked atau non-compliant.",
    ),
    (
        r"Evidence owner confirmation for high-priority or blocked supporting documents\.",
        r"Konfirmasi evidence owner untuk dokumen pendukung prioritas tinggi atau blocked.",
    ),
    (
        r"Commercial approval for pricing, tax, validity, and assumptions\.",
        r"Approval Commercial untuk pricing, pajak, validity, dan asumsi.",
    ),
    (
        r"Security / Compliance approval for data, AI, security, and regulatory obligations\.",
        r"Approval Security / Compliance untuk kewajiban data, AI, security, dan regulasi.",
    ),
    (
        r"This decision gate evaluates whether to pursue (.*?) from (.*?)\. Current readiness recommendation is '(.*?)' with a score of (\d+)\.",
        r"Decision gate ini mengevaluasi apakah tender \1 dari \2 layak dikejar. Rekomendasi readiness saat ini adalah '\3' dengan skor \4.",
    ),
    (
        r"Submission deadline: (.*?)\.",
        r"Batas submission: \1.",
    ),
    (
        r"The system identified (\d+) requirement\(s\), (\d+) response item\(s\), (\d+) proposal section\(s\), and (\d+) evidence item\(s\)\.",
        r"Sistem mengidentifikasi \1 requirement, \2 response item, \3 proposal section, dan \4 evidence item.",
    ),
]


def _to_indonesian_text(text: str) -> str:
    if not text:
        return text

    output = str(text)

    for old, new in DIRECT_ID_REPLACEMENTS.items():
        output = output.replace(old, new)

    for pattern, replacement in REGEX_ID_REPLACEMENTS:
        output = re.sub(pattern, replacement, output)

    # Light generic phrase cleanup
    output = output.replace("Please confirm", "Mohon konfirmasi")
    output = output.replace("Please clarify", "Mohon klarifikasi")
    output = output.replace("Please provide", "Mohon sediakan")
    output = output.replace("Need to confirm", "Perlu konfirmasi")
    output = output.replace("Need supporting evidence", "Membutuhkan evidence pendukung")
    output = output.replace("before sending to client", "sebelum dikirim ke klien")
    output = output.replace("Generated from", "Dihasilkan dari")
    output = output.replace("generated from", "dihasilkan dari")
    output = output.replace("requirements", "requirement")
    output = output.replace("clarification questions", "clarification question")
    output = output.replace("supporting documents", "dokumen pendukung")
    output = output.replace("submission", "submission")
    output = output.replace("review", "review")

    return output


def localize_payload(value: Any, output_language: str) -> Any:
    if output_language != "id":
        return value

    if value is None:
        return None

    if isinstance(value, str):
        return _to_indonesian_text(value)

    if isinstance(value, list):
        return [localize_payload(item, output_language) for item in value]

    if isinstance(value, tuple):
        return tuple(localize_payload(item, output_language) for item in value)

    if isinstance(value, dict):
        localized = {}
        for key, item in value.items():
            # Keep machine-readable keys as-is.
            localized[key] = localize_payload(item, output_language)
        return localized

    return value


EXPORT_LABEL_ID = {
    "Executive Decision Gate": "Decision Gate Eksekutif",
    "Executive Summary": "Ringkasan Eksekutif",
    "Decision Status": "Status Keputusan",
    "Recommendation": "Rekomendasi",
    "Readiness Score": "Skor Readiness",
    "Confidence": "Confidence",
    "Owner": "Owner",
    "Due Date": "Due Date",
    "Generation Mode": "Mode Generate",
    "Key Reasons": "Alasan Utama",
    "Blockers": "Blocker",
    "Required Approvals": "Approval yang Dibutuhkan",
    "Next Actions": "Tindak Lanjut",
    "Decision Notes": "Catatan Keputusan",
    "Proposal Sections": "Section Proposal",
    "Response Plan Appendix": "Lampiran Response Plan",
    "Evidence Checklist Appendix": "Lampiran Checklist Evidence",
    "Tender Metadata": "Metadata Tender",
    "Submission Requirements": "Persyaratan Submission",
    "Decision Gate": "Decision Gate",
    "BidReady AI - Executive Decision Gate": "BidReady AI - Decision Gate Eksekutif",
    "Bid / No-Bid decision support generated from readiness, requirements, response plan, proposal outline, and evidence pack.": "Dukungan keputusan Bid / No-Bid yang dihasilkan dari readiness, requirement, response plan, proposal outline, dan evidence pack.",
    "Decision gate has not been generated yet.": "Decision gate belum digenerate.",
    "Evidence": "Evidence",
    "Category": "Kategori",
    "Priority": "Prioritas",
    "Status": "Status",
    "Notes": "Catatan",
}


def localized_label(label: str, output_language: str) -> str:
    if output_language != "id":
        return label

    return EXPORT_LABEL_ID.get(label, localize_payload(label, output_language))


EXPORT_LABEL_ID = {
    "Executive Decision Gate": "Decision Gate Eksekutif",
    "Executive Summary": "Ringkasan Eksekutif",
    "Decision Status": "Status Keputusan",
    "Recommendation": "Rekomendasi",
    "Readiness Score": "Skor Readiness",
    "Confidence": "Confidence",
    "Owner": "Owner",
    "Due Date": "Due Date",
    "Generation Mode": "Mode Generate",
    "Key Reasons": "Alasan Utama",
    "Blockers": "Blocker",
    "Required Approvals": "Approval yang Dibutuhkan",
    "Next Actions": "Tindak Lanjut",
    "Decision Notes": "Catatan Keputusan",
    "Proposal Sections": "Section Proposal",
    "Response Plan Appendix": "Lampiran Response Plan",
    "Evidence Checklist Appendix": "Lampiran Checklist Evidence",
    "Tender Metadata": "Metadata Tender",
    "Submission Requirements": "Persyaratan Submission",
    "Decision Gate": "Decision Gate",
    "BidReady AI - Executive Decision Gate": "BidReady AI - Decision Gate Eksekutif",
    "Bid / No-Bid decision support generated from readiness, requirements, response plan, proposal outline, and evidence pack.": "Dukungan keputusan Bid / No-Bid yang dihasilkan dari readiness, requirement, response plan, proposal outline, dan evidence pack.",
    "Decision gate has not been generated yet.": "Decision gate belum digenerate.",
    "Evidence": "Evidence",
    "Category": "Kategori",
    "Priority": "Prioritas",
    "Status": "Status",
    "Notes": "Catatan",
}


def localized_label(label: str, output_language: str) -> str:
    if output_language != "id":
        return label

    return EXPORT_LABEL_ID.get(label, localize_payload(label, output_language))


# Extra phrase replacements for Response Plan artifacts.
RESPONSE_PLAN_ID_REPLACEMENTS = {
    "Compliant": "Compliant",
    "Partially compliant": "Partially compliant",
    "Non-compliant": "Non-compliant",
    "Need review": "Perlu review",
    "Prepare response": "Siapkan response",
    "Prepare a response": "Siapkan response",
    "Provide evidence": "Sediakan evidence",
    "Provide supporting evidence": "Sediakan evidence pendukung",
    "Confirm compliance": "Konfirmasi compliance",
    "Confirm internally": "Konfirmasi internal",
    "Need internal confirmation": "Perlu konfirmasi internal",
    "Requires internal confirmation": "Membutuhkan konfirmasi internal",
    "Owner should review this requirement": "Owner perlu mereview requirement ini",
    "Bid manager should review this requirement": "Bid manager perlu mereview requirement ini",
    "Commercial team should review this requirement": "Tim commercial perlu mereview requirement ini",
    "Delivery team should review this requirement": "Tim delivery perlu mereview requirement ini",
    "Solution architect should review this requirement": "Solution architect perlu mereview requirement ini",
    "Prepare required supporting document": "Siapkan dokumen pendukung yang dibutuhkan",
    "Prepare required supporting documents": "Siapkan dokumen pendukung yang dibutuhkan",
    "Attach supporting document": "Lampirkan dokumen pendukung",
    "Attach supporting documents": "Lampirkan dokumen pendukung",
    "Validate with owner": "Validasi dengan owner",
    "Validate with bid manager": "Validasi dengan bid manager",
    "Validate with commercial team": "Validasi dengan tim commercial",
    "Validate with delivery team": "Validasi dengan tim delivery",
    "Validate with solution architect": "Validasi dengan solution architect",
    "Risk should be reviewed before submission": "Risiko perlu direview sebelum submission",
    "Review before submission": "Review sebelum submission",
    "Include in proposal response": "Masukkan ke response proposal",
    "Include in technical proposal": "Masukkan ke proposal teknis",
    "Include in commercial proposal": "Masukkan ke proposal commercial",
}


# Patch localize function by extending direct replacements at runtime.
DIRECT_ID_REPLACEMENTS.update(RESPONSE_PLAN_ID_REPLACEMENTS)


# Response Plan additional phrase replacements.
RESPONSE_PLAN_ID_REPLACEMENTS = {
    "Prepare response": "Siapkan response",
    "Prepare a response": "Siapkan response",
    "Draft response": "Draft response",
    "Provide evidence": "Sediakan evidence",
    "Provide supporting evidence": "Sediakan evidence pendukung",
    "Supporting evidence": "Evidence pendukung",
    "Evidence checklist": "Checklist evidence",
    "Need internal review": "Perlu review internal",
    "Needs internal review": "Perlu review internal",
    "Need internal confirmation": "Perlu konfirmasi internal",
    "Requires internal confirmation": "Membutuhkan konfirmasi internal",
    "Confirm compliance": "Konfirmasi compliance",
    "Validate with owner": "Validasi dengan owner",
    "Review before submission": "Review sebelum submission",
    "Include in proposal response": "Masukkan ke response proposal",
    "Include in technical proposal": "Masukkan ke proposal teknis",
    "Include in commercial proposal": "Masukkan ke proposal commercial",
    "Owner should review this requirement": "Owner perlu mereview requirement ini",
    "Bid manager should review this requirement": "Bid manager perlu mereview requirement ini",
    "Commercial team should review this requirement": "Tim commercial perlu mereview requirement ini",
    "Delivery team should review this requirement": "Tim delivery perlu mereview requirement ini",
    "Solution architect should review this requirement": "Solution architect perlu mereview requirement ini",
    "Risk should be reviewed before submission": "Risiko perlu direview sebelum submission",
}

DIRECT_ID_REPLACEMENTS.update(RESPONSE_PLAN_ID_REPLACEMENTS)

def localize_response_plan_payload(payload: dict, output_language: str) -> dict:
    """
    Localize generated Response Plan fields only.
    Keep source traceability fields such as requirement_text and evidence_quote unchanged.
    """
    if output_language != "id" or not isinstance(payload, dict):
        return payload

    localized = dict(payload)

    exact_text_map = {
        # Strategies
        "Prepare a solution response that maps service scope, architecture, support model, SLA, roles and responsibilities, and operational approach.": "Siapkan response solusi yang memetakan scope layanan, arsitektur, model support, SLA, peran dan tanggung jawab, serta pendekatan operasional.",
        "Confirm pricing structure, tax inclusion, commercial assumptions, exclusions, proposal validity, and payment terms before final submission.": "Konfirmasi struktur pricing, cakupan pajak, asumsi komersial, exclusion, masa berlaku proposal, dan termin pembayaran sebelum final submission.",
        "Review requirement with bid owner, prepare supporting evidence, and align response with proposal strategy.": "Review requirement bersama bid owner, siapkan evidence pendukung, dan selaraskan response dengan strategi proposal.",
        "Prepare a delivery methodology covering transition approach, timeline, governance, handover, and acceptance criteria.": "Siapkan metodologi delivery yang mencakup pendekatan transition, timeline, governance, handover, dan acceptance criteria.",
        "Confirm resource availability, role fit, certification evidence, CV format, and substitution rules.": "Konfirmasi ketersediaan resource, kesesuaian role, evidence sertifikasi, format CV, dan aturan substitusi.",
        "Validate administrative submission checklist, document format, deadline, signing, and mandatory attachments.": "Validasi checklist administrasi submission, format dokumen, deadline, penandatanganan, dan lampiran wajib.",

        # Evidence needed
        "Solution architecture": "Arsitektur solusi",
        "Service scope and responsibility matrix": "Matrix scope layanan dan tanggung jawab",
        "SLA / support model": "SLA / model support",
        "Certification document": "Dokumen sertifikasi",
        "Commercial proposal": "Proposal komersial",
        "Pricing assumptions and exclusions": "Asumsi pricing dan exclusion",
        "Tax and validity confirmation": "Konfirmasi pajak dan validitas",
        "Relevant proposal section and supporting evidence": "Section proposal terkait dan evidence pendukung",
        "Implementation methodology": "Metodologi implementasi",
        "Delivery plan and timeline": "Rencana delivery dan timeline",
        "Acceptance criteria": "Acceptance criteria",
        "Resource CV": "CV resource",
        "Certification evidence": "Evidence sertifikasi",
        "Resource availability confirmation": "Konfirmasi ketersediaan resource",
        "Submission document checklist": "Checklist dokumen submission",
        "Administrative document copy": "Salinan dokumen administrasi",

        # Assumptions
        "Response must be reviewed and approved by the responsible owner.": "Response harus direview dan disetujui oleh owner yang bertanggung jawab.",
        "Final client-facing language may need adjustment based on official proposal format.": "Bahasa final untuk klien mungkin perlu disesuaikan dengan format proposal resmi.",

        # Risks
        "No major risk identified from current requirement status.": "Tidak ada risiko besar yang teridentifikasi dari status requirement saat ini.",
        "Requirement has not been reviewed by responsible team.": "Requirement belum direview oleh tim yang bertanggung jawab.",
        "High-risk requirement requiring focused owner review.": "Requirement high-risk yang membutuhkan review terfokus dari owner.",

        # Notes
        "Generated by rule-based response plan generator v1": "Dihasilkan oleh generator response plan berbasis rule v1",
    }

    def translate_text(value):
        if not isinstance(value, str):
            return value

        text_value = exact_text_map.get(value, value)

        patterns = [
            (
                r"^We acknowledge the service requirement: (.*?)\.* Our response will describe the proposed solution, service scope, operating model, support process, and responsibilities\.$",
                r"Kami memahami requirement layanan: \1. Response kami akan menjelaskan solusi yang diusulkan, scope layanan, operating model, proses support, dan pembagian tanggung jawab.",
            ),
            (
                r"^We acknowledge the commercial requirement: (.*?)\.* Our commercial response will clearly state pricing basis, tax treatment, assumptions, exclusions, payment terms, and proposal validity\.$",
                r"Kami memahami requirement komersial: \1. Response komersial kami akan menjelaskan dasar pricing, perlakuan pajak, asumsi, exclusion, termin pembayaran, dan masa berlaku proposal.",
            ),
            (
                r"^We acknowledge the delivery requirement: (.*?)\.* Our proposal will include the delivery methodology, implementation plan, governance model, handover approach, and acceptance criteria\.$",
                r"Kami memahami requirement delivery: \1. Proposal kami akan mencakup metodologi delivery, rencana implementasi, model governance, pendekatan handover, dan acceptance criteria.",
            ),
            (
                r"^We acknowledge the staffing/certification requirement: (.*?)\.* We will provide resource profile, role mapping, certification evidence, and availability confirmation as required\.$",
                r"Kami memahami requirement staffing/sertifikasi: \1. Kami akan menyediakan profil resource, mapping role, evidence sertifikasi, dan konfirmasi ketersediaan sesuai kebutuhan.",
            ),
            (
                r"^We acknowledge the submission requirement: (.*?)\.* The bid team will prepare and validate the required administrative documents prior to submission\.$",
                r"Kami memahami requirement submission: \1. Tim bid akan menyiapkan dan memvalidasi dokumen administrasi yang dibutuhkan sebelum submission.",
            ),
            (
                r"^We acknowledge the requirement: (.*?)\.* The response will be reviewed by the responsible owner and supported with relevant evidence\.$",
                r"Kami memahami requirement: \1. Response akan direview oleh owner yang bertanggung jawab dan didukung dengan evidence yang relevan.",
            ),
        ]

        for pattern, replacement in patterns:
            text_value = re.sub(pattern, replacement, text_value)

        return text_value

    def translate_value(value):
        if isinstance(value, str):
            return translate_text(value)
        if isinstance(value, list):
            return [translate_value(item) for item in value]
        if isinstance(value, dict):
            return {key: translate_value(item) for key, item in value.items()}
        return value

    generated_fields = {
        "response_strategy",
        "draft_response",
        "evidence_needed",
        "review_notes",
        "assumptions",
        "risks",
        "notes",
    }

    for field in generated_fields:
        if field in localized:
            localized[field] = translate_value(localized[field])

    return localized

def localize_proposal_outline_payload(payload: dict, output_language: str) -> dict:
    """
    Localize generated Proposal Outline fields.
    Keep ids, owner, status, ordering, and machine-readable fields unchanged.
    """
    if output_language != "id" or not isinstance(payload, dict):
        return payload

    localized = dict(payload)

    exact_text_map = {
        # Notes
        "Generated by rule-based proposal outline generator v1": "Dihasilkan oleh generator proposal outline berbasis rule v1",

        # Section titles
        "Executive Summary": "Ringkasan Eksekutif",
        "Understanding of Requirements": "Pemahaman Requirement",
        "Proposed Solution": "Solusi yang Diusulkan",
        "Delivery Approach": "Pendekatan Delivery",
        "Security and Compliance": "Security dan Compliance",
        "Commercial Response": "Response Komersial",
        "Assumptions and Clarifications": "Asumsi dan Klarifikasi",
        "Submission Checklist": "Checklist Submission",

        # Purposes
        "Provide a concise business-level overview of the proposed response and why the bidder is suitable.": "Memberikan ringkasan level bisnis yang singkat mengenai response yang diajukan dan alasan bidder sesuai untuk tender ini.",
        "Describe the bidder's understanding of the client's needs and objectives.": "Menjelaskan pemahaman bidder terhadap kebutuhan dan objektif klien.",
        "Explain the proposed solution and service scope.": "Menjelaskan solusi yang diusulkan dan scope layanan.",
        "Describe delivery approach, transition plan, governance, and acceptance.": "Menjelaskan pendekatan delivery, rencana transition, governance, dan acceptance.",
        "Describe security, compliance, data protection, and risk controls.": "Menjelaskan security, compliance, data protection, dan kontrol risiko.",
        "Summarize commercial assumptions, pricing basis, validity, and exclusions.": "Merangkum asumsi komersial, dasar pricing, masa berlaku, dan exclusion.",
        "List assumptions, dependencies, risks, and clarifications.": "Menjabarkan asumsi, dependency, risiko, dan klarifikasi.",
        "Provide submission checklist and supporting evidence reference.": "Menyediakan checklist submission dan referensi evidence pendukung.",

        # Executive summary bullets
        "Summarize understanding of Managed Cloud Application Support and Security Operations.": "Ringkas pemahaman terhadap Managed Cloud Application Support and Security Operations.",
        "Position the response around Managed Services / Cloud / Security.": "Posisikan response pada area Managed Services / Cloud / Security.",
        "Highlight key strengths, delivery confidence, and readiness.": "Highlight kekuatan utama, confidence delivery, dan readiness.",
        "Mention that detailed compliance, evidence, and assumptions are addressed in later sections.": "Jelaskan bahwa detail compliance, evidence, dan asumsi dibahas pada section berikutnya.",
    }

    def translate_text(value):
        if not isinstance(value, str):
            return value

        text_value = exact_text_map.get(value, value)

        patterns = [
            (
                r"^This proposal responds to (.*?) issued by (.*?)\. The response is structured to demonstrate understanding of the requirements?, proposed solution, delivery approach, governance, compliance considerations, and supporting evidence\. The current response plan contains (\d+) mapped response item\(s\)\.$",
                r"Proposal ini merespons \1 yang diterbitkan oleh \2. Response disusun untuk menunjukkan pemahaman terhadap requirement, solusi yang diusulkan, pendekatan delivery, governance, pertimbangan compliance, dan evidence pendukung. Saat ini response plan berisi \3 response item yang sudah dipetakan.",
            ),
            (
                r"^This section describes (.*?)\.$",
                r"Section ini menjelaskan \1.",
            ),
            (
                r"^Describe (.*?)\.$",
                r"Jelaskan \1.",
            ),
            (
                r"^Summarize (.*?)\.$",
                r"Ringkas \1.",
            ),
            (
                r"^Explain (.*?)\.$",
                r"Jelaskan \1.",
            ),
            (
                r"^List (.*?)\.$",
                r"Daftar \1.",
            ),
            (
                r"^Provide (.*?)\.$",
                r"Sediakan \1.",
            ),
        ]

        for pattern, replacement in patterns:
            text_value = re.sub(pattern, replacement, text_value)

        return text_value

    def translate_value(value):
        if isinstance(value, str):
            return translate_text(value)
        if isinstance(value, list):
            return [translate_value(item) for item in value]
        if isinstance(value, dict):
            return {key: translate_value(item) for key, item in value.items()}
        return value

    generated_fields = {
        "title",
        "purpose",
        "content_outline",
        "draft_content",
        "evidence_needed",
        "risks",
        "notes",
    }

    for field in generated_fields:
        if field in localized:
            localized[field] = translate_value(localized[field])

    return localized

